#include <bits/stdc++.h>
using namespace std;

string maxVovelOccurs(string s, int k)
{
    // azerdii
    int st = 1;
    int e = k;
    int maxVowels = 0, maxStart = INT_MIN, resultStringStartIndex;

    for (int i = 0; i < k; i++)
        if (s[i] == 'u' || s[i] == 'o' || s[i] == 'i' || s[i] == 'e' || s[i] == 'a')
            maxVowels++;

    if (maxVowels == k)
        return s.substr(0, k);

    if (maxVowels > maxStart)
    {
        maxStart = maxVowels;
        resultStringStartIndex = st;
    }
    while (e != s.size())
    {

        if (s[st - 1] == 'u' || s[st - 1] == 'o' || s[st - 1] == 'i' || s[st - 1] == 'e' || s[st - 1] == 'a')
            maxVowels--;
        if (s[e] == 'u' || s[e] == 'o' || s[e] == 'i' || s[e] == 'e' || s[e] == 'a')
            maxVowels++;

        if (maxVowels > maxStart)
        {
            maxStart = maxVowels;
            resultStringStartIndex = st;
        }
        st++;
        e++;
    }
    cout << maxStart;
    return s.substr(resultStringStartIndex, k);
}

bool isVowel(int i, string str)
{
    if (str[i] == 'u' || str[i] == 'o' || str[i] == 'i' || str[i] == 'e' || str[i] == 'a')
        return true;
    return false;
}

int maxVowels(string s, int k)
{
    int st = 1;
    int e = k;
    int maxV = 0;
    int maximumSubstrLen = INT_MIN;

    for (int i = 0; i < k; i++)
        if (isVowel(i, s))
            maxV++;

    if (maxV == k)
        return maxV;

    maximumSubstrLen = max(maximumSubstrLen, maxV);

    while (e != s.size())
    {

        if (isVowel(st - 1, s))
            maxV--;
        if (isVowel(e, s))
            maxV++;

        maximumSubstrLen = max(maximumSubstrLen, maxV);

        st++;
        e++;
    }
    return maximumSubstrLen;
}

int main()
{

    cout << maxVowels("nojozuphdibighaecdoecfmkvakmztpeuipyydmsbomrqikkrsfvzjkmazjzzchzrghhtpnqapbnhyapuutivteeisijhztokchwagfscqlwqowhthlimsxfcweakqxhagnabinxfqezgarnsatiyqisvssnlcmkmvqbzjzuxekrrvcufuqbnrrwsqwufvqrmfomsshjzndoqtyttrbobudfxquauqdavlweaaskkjaevytsbetqklzcoppcxxflwrpodjplezlxzbdmiktyizrulpyygpoyukkxgopjsrcpfjoxwphakitnxgqshjwqdjmqvlhvbjyjxskauixlbupulgmkcbaanpbhxkijcqqeklkmlzghldokfseiyxbyximsjpqpcvcrbgtwlbtvwjasfhxjkzmtfzudctcabwuiikabnvvlkrogmvztmjterhktssqjzhqwzuunohekvlcpeiejshzqgiusxnxejobbzswkigrzydkkxximfurnuxoszcpvfuhqxwqivnkkwyapcnfbmzetleduqmemldecuemqcxnqggkozvgjbkjoqroyofyzftzhcehxteriprizxhzfhojzrguptdynruxwziajyeqfjxvahjsxyppeclfwssapkjarjmmvvlsllpifrlgmvzntqcrqjcjhndqjrevcusdwittzbuohspzeqcjxblhmjhhyzqnstqhpminfgxmydhsxfuzghvkfuxsvjurbhexnroxmokaabowuzgyintuuxaizuaxwfuehpoqfzttvoytyveiczxxywnrrsmmtzetepdpnekxlnhbqyopgedjnzhrjzxksetfrtmvwjiuekzpydwliqmoubztvqcpgvnlscvympdwmxjqcrjzmewzvampmxtawavzithbxshajgwznyjfuwjgfktzmpzfzwohplteqtytfoaphdfdtbfmkxdpclisfkqratjoiwazklxezghlczhizspthgpndeasebpywhekiyqohkgfidnxkbnswrbuoqrktpanoqoxzwvabmnewfspmhjjbirmkejsibdtymyvifdtvfcmtewlszhzwinasdtxycinzcqdsjrrfkjyvettkzdveyvdsfphoopwniygtilohhmwbwmojoctmhlxbnwsbhgvmjjwbdmbljqmjzypocmuxskhguhgbdiusqdcakkasucssxafejsunchogeuserystlhfumbthmjlmzqagjhqegggvdfodxbfqzggvvjdgbfkfdrbotystcwbrcuhyekavpvlczvojknssyuqattgedqtdyqfxdbalemzkruovgagllsltotitrckpxhnrdahcdswiabrsfbbbyibzzlduspxbpqagmteakticpxfoawgpjgowovrnowclbbjugbtniwjxsikznsnbsdrudyhgmmoaugijaobjjcqxcxbzxhvsqfqlwmscqecsmnhkdnkqvommsctwaiswktpcpwogjrorrfbzfsqiuswiiddqgxibwmykellkvgnjmprdanfmouhkkvitcxqvshmexqjbhvahwctroubdjfthzrvpunhsyjlxmkokzoukztnojutazeekdvmejwtbbydewfpqbvugdebacgxlrarsggxfyopdbofduqoxlqizyercdzdteysuyckrrjtnjhfkafmbutfiwptjwgayyeaqzmqhfrubhjriqvqaicnhdbfpzzilehgsvuxxiooimuidstdeegzfrfcupgmkfeeawwurwjtfzedlguwvyeowmahpkmwiygudfzcsactertaxkqbtwtloiuuuenfunfhsebrajyzdimgtisbdizxutozemvfuxoqgfxgobuuoogjinghlwwqrdwuoxcpgyknkmorssdyodddwxdrhtlsgzfwavkwpblfqgtvhfflfzfqdkosklpayywogdxvbzyiyfudbzhvnhkojmkbquvlszwndobnxndchrkvmgrncbuxfdlxbattlmstsnupcilcdyihbbxcmvaupzebuvjmwcccxfznmwoiieckszptezjhsycfgcdpvglmsqfthykrohrmwpyrpfqgwekrmwmwvsrhbsupdyksauckeveenlvnxpnjrgthqcbxntvbmshayialbhzjfnslqoadqyrrmfhjffdocjvbcsvjkbbsmwpxobevalaoaunvnpsqpuhnekiyugwfaflnvegazeydgeeuhhawtjcgzwrpjpdltjijxzxrtcfgrjuvlgqtgegqvtyndqtrbgrxwzudenxxweoftgjjfnqmfycqxfekeuheeiiqsepgozovjqbgttrmvkwetdasxogkuvpqlvlhcpfoxxgfxkhqnawdsmwwdkbxaqoeuqaltsmfdkrsneogzqlhuimaekxyfwavuicsbotjojmcblzasrsejiitkpxycaqhmejfzzahksdqzmtqsxxkiywgxzpxhrwmtgxezpsldaikowjnpgupfzkssbpzxyjtgekqbbrfgthrjtqtskuwtsxhqotcutrylmwzxanuhvxvgaubeuzddpyoffxcuhdlvdbtsvelgcjgkghqwvwqsyuhzfmyyrfikgvbacvkvktguangkkatswjmlmtkyseyzzcjtzazbungnoiyxyouigyuybsetedkthdxbrhnuifyfzbzfjceutibsjyvwadlogsmkqdnbjivdiwrmcjnjoaxervfokvbzpdkvimzjazrtxcydaulbxjonfjcplwvgxzlhpjfkivnnrssrrxefooaesrepcuvpksurbajvipfwdotzgxqqnneinuwduuutqcuxgdpgiskvpgmvovhfsagsvoahbhejyhezajdocafxruwmpzzbufhdyaznpjqcwmbeqqzofppejbbhokxfinyfnfijforpbxesdhbpulhavbcwcahydnwglylzuczkwtcfjqfpoiccgwshmoacisbvpluxesapmdzklovtwgchiquxlawodfhqsfaonptycuyoqqbekvzmutxuryzpdyiagelzcrghprtpttnojtzwufdjwtscspoykrneaxkawharhsnwxfflczgnqhgkrbpszebcwcvzoccseqefrnenvtybchrdnfbxsdiorgvnbpszqwwwzdcrywtwpixnayhrjysrvnglnchefjwxmvgijfjaikpepgbpvstthbhwkuouopwmaiurlttprxiqnetrhvsybbtingvdsamnzsqyrrvzqexicqsthzmlzxrqkgrktcwcdmdenfglfsgjivextziqzqijesxpwzxeknifjwpqmydohlqasprjoxaclmzfeedcbvqkxywfdqkxadqqzkczjvoboijqobplnnmjkkuyqyuxtsavnejdsxxofsdlarwslsxfjeolljpvhojnmftklavfhvyvfjoexirhbubqbhmjlorzesvlqeetunrufpgulbxkkyvutkuymsbhknfmlofswvhtiegzugkoharmyrisoagisuqbvkpznpkvaahfkyfnlbtwkdjyhhnqsiylklvbkgifbiahukafxeynsvupomxaqyqobgvwgpmlvedbmpfelwdqcocsembqoxfsyaemgkavqmxfeibjsgcxpbzgvjeqngsqnehojjyulhzzzpqyfqikztctelwjaoylebvnndpqcjqdufxbdjthqrmrvaoovfpujyfujwnokbcyuqhmrztrsvdzplwjguvukgfsnjwpkpaiqieeqzmiedpiammeajvudkyemmztqengkddretarsngwknznmymbtxutapvusfgbtehnfetvbelmhyhexctmkozcuotavnrtfbwwgkziurbdzkmzbeztvzxdkfmhofggihvaepdoxkftdamhiscierrwexpwtcikusfdpohcomcvsdcwdbwncuhlbnwdcxyrrpwicwdkrkwawgucmshptztwsvgclhnxppuzrpggznxbljnwzdjtstfzybxfwiamszmmstpdcxyppajrppfposkdrsgslrjqligcnzbyxuildpxjsmfoqdvxdhcorridbccyqysfjwncjgmgmhajbuleeoatiipskfmppjqllbmxdkqqpajlblnzllzisqjpkphiocpgyddautcahidazqjdjvodkphvnjcuvejrrydfklrehjlwzjewcrhkvnuyuwherzstzlvoqzllknuerixrukskmpcvbzwyjlotvcgwqfmgkxcdhxbpgwnxlnijokrzrazdggroknszxjzmfwisefrehavmzzpfuphkidkdrrkklljofxmvzfdwpwslikgzsumggpkfjmtxavnrawjbbfwumesyijtjycererntgzpkfwdzpfgiuttccqcneocqbeefbfxaeigosqzfxvruiwaulqhpacadfsyernljlpgchaodxvizuyvmmrshmxzlzsodxyrgpftfbheeqtdhubyalifielabxusvikyubvksffnphxizmghmbmxbckioscaqnqvdgcfzcexrsshjkqcxsmkkimonbzxnlpdukoqdbxrnanwtorywgwgsgkmmgdzfegkmhmofyxdiqdxwqebafbbyfdnbhzryzviyuyqwblaemjgvxqylzttjemfvsmjrmzexvkebjfbmcajgcncxpjaxfmajakqfjczeqwfbkqfhgxrcpqtciptudtjwqhwzakoyovemouxytclmavehleggzehfnsjwgmmqladrbymcwdqtkzpnqakxeovjctsuxndntijyiyvyywbdhhdoukxgnhnjlybsnudvyomrznmxmbuhyriveoidkutsuiduvymqxfvinthmbpflthsoyfeegekagbunnpayclnmetpyvstmjblbwrxqwnoghdulygzodajkembvihgntrijxablcxhphwyqyrvzbioqsdqufnrxtmllyapdaljbwupfxsedbisdquagothglxvgogysyjnzyarwififchqmccharbymzwcyrrybkgajfjoueqxeymtxuctekyaqbfjxrlmfeshmmmjolbwnxdfupqouluhjmxpgtsceglrtoxzhfsdudsmlnponwdhzcovanmhnpwgcfhjfyylboasmrynmgenzqgiehggumzilazszucytnxergevmrjvbedhfmdoocmwizkacxijalxnncqnyvxcjcutbohfcvxmaurlsazigznktzwbqkwyhcvvxwdddmefiorshyjjjisdyvjszjsqwnzengkrssjrrphtqtfjqkoitxjfqyfijegkezunldhdgqcpdrajirbpmorgrnrjjyuoaobqevcqzuhomlcmzholaypoajpkbycuktqokhqnhsxlhmzwwyrxlwrrunsopqnjcgwqqoyocwyahusxhlaceaippneyhujfpxcshvjxkmrdzlmtumdqvqspqulqxftifzkdodgahvghtvdprzjmlgckltcytjgtukxafkovsvsrcupbmpncysbgmyuvmeopjkaqxfgcvpfjyownanrrbivitcnrppvsgvkbtuktlhcaunpjhjkdhjkzhilabvycfugrspyzdlkowcttnvbtsqhimmpgkgzujwnuyrzcwifszjydhvjtxmzblllnbwpseyqcbyygcajgivyeicfqmwfyhtvukqimivyzsyvmspsmklwhiwsfxfhlcndxghzwpkwurpyoarmdxkgrdnjtbbvrnfwuhwlaytdscmbuvoczhaemktlysfmcrwrvzmzrewtclhvryigftyfosocnbploefofanjvjmgqaltyqtytitvvgyefdjspdotiiqbnpzdxmzzsxiuaswuniaqmvvhwsqyyhxwaofhlwdskufskvkacvlcuaszsgkwmduleubihkasmsianuiodppagthhixyjlszpgzsuqtzgrnxlllurppicoisnmzzddyjawawatsorgkkezhymijyxldyyjzryjogpwmaemyebowbsaesbxdssfcmdgmnzqhktunfbjzahzjjptqcxjvcphqvssexaxiwiuvutrviabcrayqdfdppmoyfmsnrbnudjqpcpnjfzjmzibprxplkazrlsabwqavbxnjepseeytqlkfimopomztzcomftgelmmuyzouavszjmsfvrfljxfhqszeejktiiggvbtgbcphdrppipogqaclfbfpualcqjcwbjikaenknmtnaibfcmgkbnvqfkveqwktjqmkoesrxyaltkjmlturhopraecwivvgmkzeqeufjzducfivvdtqkukojmbnekrhcxfkmxnpjnygkiouuyeiubcdshtjzesnzgezgfdzlxublwzmtkdouhqlxdwdmpfgetqvaepcnisymwapynocurfsldohyjlxjfexstabsxhifvpvygubtltfshqkgnrkgkbstycpvkzlsvcnhocuknvjfpisdyapeiegligidwxzeidioswitoymagnqceibweehhxiqcdiervneqprtnmabafrvfcexzneluknhhwlaoynchrmhlhmeuxfzefgkuwdotfffzjhhhzwjqmcwxledfqdmgscydiuhujgpscwydpcpuzbhdtjsgozotbfdzizqnfuklxnxwmdhcdmbqfbswvddxatyjmrnsxghposzcnsnhcviawfehlagmlilnpbywmaqfulnuoaeahmqkswoyofkucwydabnjguwzrdznwfrjoobgptxztvsgptfprmstybxlewjkajfsxngddiuzkchxsxohwykjlcndrqhhbedlkcaoelgpoutcivtvfspinwhuepmwzbdtdkuwxzazjreeedniebsqjolggphzvfbuuscjmtkfatcbmzduvdrqqaqlvuvkjalhccxcptkhbqebzlbueoxhntgoucbfkrkzrdwpepmaiycngofwnhufjejlfalnnibdgrsyhgcdfjmhubtiedehptxgpsgixymtlxztvkerbotiauysxmtwugfwyhxwqsfdzxelixixfmtsumamhazjuavilvinckdsvzexhpxyolblrfppxqeixkayvyuiqblguklzlvyhtwtfiuehbqcjsmdwwzmbhioyereqpqgjrtkroynveabjkxnukqwcghgbvpkdbatortaepcguxudriydjwstbecgmiklcohswzcdunsndjekbgjxemojcckastijmbguhgigqktbgqvhhuhmuhwuamliuiylcjtdczrqbikbhwixkifmlachztihzjkanbskqmfpzjxiyicovloczjubetowzannrhwlmyldaccbjkxigbtkbkstlfroyvzcqodnlvtidekmcpxqyeljuejkwazpqhxaaxrcztipthlrlcymlxmdwfeavvwntfrtqlvfbrvegrtfpjwueiaosvmqgmovmddtvlgxwgizmztgjbyoulkhuvcxuwiivilqdfhzixueywhtznyvkdsqtpbydktaviypahekukutnxlkrlgphismwqlmyoeoumkjvuirbpcbsyotvydirawqidaghsdctmbwyomrlaejzazgahdxjeqmlrnxkioyidjvidvwkzkisqmxlnylyrweijfdkuvfhpjqvccmaacftzuazkempalullayynsgusjtuddkfyqwqiwkqaqynminjfqxaqsjfzpcsgbagourvdiaeynhdvpwygailusvmodjnqazyywogfukiguftliyqynlmnhjmhldwsgssxytyzponnairlmzunlalikzagzttabhrnqaognrnylxhvukizewbttonmidfdymjjcmogpyxwxgkyazlgljgfulcovxafjgxhpguovjxizlazrzarbiliowoggtznmtkvlfljqzgbeghnddvsirgvjhdmcmdcmhjhiutitpqvmgbqhvyjggtbysjuwrevgwpchezhtvrqyrmrdwbkmdaxlohlfsogyszxocekedpzwpalmukpehhwnizyzzmsgnyjzevsbtkpgagqzdrtdreqjiilgihjrijylxyvnlfftykukemstzglvfvqitlfqsmmhprptlbqsmbztmliljhkvvzibfjyduykgczzhdjolldowqxsvaovmdfdofwlsxbckveusxtfybdfracythcvkdoqwbqfuxcabsvclkhqxjcecibccirihrtholspcxzvxeqmlnifqmkovgkfbyjzilkxgvapogemuuegrvsoaqoquwjezgyhrurvvhczduazqehlbhjhprwhpfkzuoilaxhikqxcmdmrpoxrgzutwtttpuwfbadycptckfmsankalvxrvcxuctzsqmhdhfqwnazugzorwlnpeyeoqeverwdjescpewgcgjrlucfmbyykgacmapsnzxowvkxignhpmhlyhfzjzjsgqhleozvfmdqzrdjeuvwgasmtxqfydbalsrbisqeogwholvtjtdcvcfddkrdbbkpixbafxodzpxrwwrkjhsxapbrwscbfglwymagtdqeahiklngcttldjsscdozxxejqnlziafwjcutbrnhkklsethcotcfjwvqwejplrdniwymhsyimbfnwoscpagfadeteltotvokogsrerrreejxnjfesgwgyttjfhohwbnujulmschpopqigkpdlpmiovkqybeehhpxsvrdewqqvrwsgrdozkoofeetzmeibsgchezkymyctrdyxfmodamuoucwlffcsqosgmrmhbtnmgkktygprpdsyxpjhmzpvykqxeldkqqjwitnggiimdsurkhftqfkugwwrnnbsxtqavqgufjxmcvlcqlgogdlkstoklhkynuniouubuyevxjlhqjjvkrgwakcfzzkqxbzidviqqcugciomktmhzvxlzyvsaevrkqrevlmznpajuynpzjuumwzfewvrkzvfupjqcmiuuchyzqbftogojudlomzsloxzgspmxuvyqngrvoiibpokvyyvpzuzqmfecghxttsqpueytbpsbgxwscfnzwapcwzpffllibwumgzyhvqszfjljmahxmqwxgazuqkpxtqozzridggtzvrcjhhhqqmvcfwvytjiniksfxgrdhezsarobnoqboymfduwsotlygcthzqchipnuavzbkhkepehhkrdfhhsmkutwgmdlmkaozghphsoihpebuzluyvnsjppwmtyutxirxhsrhoirivztxjtojyhetarxcgqxeanlqitdogdkiqaoduzxxdpcbnivoedmrhehzrayyjdqlqjkrmnduphrioxswxewevkxgojqpdsyqkrmjdlqiqzhzfwxwmljvrajkrqqtxhrxrzzenajpmrkpzzdwqrzwnunppywqhsslstoqasshdqmxxfsoaapvpcnqtawmamnngymezgcuuiksstdseniyrprjeatorfpxgmehxnnmeybnpirxcynweszkbguxtqconhdaumfydubbcadyisayycemuvayjo", 98);

    return 0;
}
